### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Danghor** [karlstroetmann/Statistik#8]
The link <https://www.dartmouth.edu/~chance/teaching_aids/books_articles/probability_book/amsbook.mac.pdf> on page 4 seems to be dead. Maybe <https://math.dartmouth.edu/~prob/prob/prob.pdf> is an alternative?

**Comment by karlstroetmann** [comment]
Vielen Dank, ich habe den Link korrigiert!

**Comment by karlstroetmann** [comment]
Der vorgeschlagene Link funktioniert!
